/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.conexion.ConexionBD;
import ec.edu.ups.controlador.ControladorCorreo;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Correo;
import ec.edu.ups.modelo.DetalleFactura;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Producto;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class VistaFactura extends javax.swing.JInternalFrame {

    private Date fechactual;
    private ControladorFactura conFactura;
    private Cliente cliente;
    private Producto producto = new Producto();
    private ControladorCorreo controladorCorreo;
    DefaultTableModel modelo = new DefaultTableModel();
    private Factura facCabecera;
    float pIva, pTotal, pSubtotal;
    double cantidad;
    double precio;
    int idProd;
    float sub, iv, tot;

    private DetalleFactura detallefac = new DetalleFactura();
    private ConexionBD conexion=new ConexionBD();
    
    private Correo correo;

    public VistaFactura() {
        initComponents();
        conFactura = new ControladorFactura();
        correo =new Correo();
        txtFecha.setText(getFechaActual());
        controladorCorreo= new ControladorCorreo();
        Idfactura();
    }

    public static boolean validarNumeroNegativo(String texto) {
        return texto.matches("^-[0-9]+$");
    }

    public String getFechaActual() {
        fechactual = new Date();
        String vFechaOK = new SimpleDateFormat("dd/MM/yyyy").format(this.fechactual);
        return vFechaOK;
    }

    public void Idfactura() {
        conFactura = new ControladorFactura();
        txtNumFactura.setText(conFactura.numerarFactura());
    }

    public Date formatoFecha() {
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/mm/yyyy");
        String strFecha = txtFecha.getText();
        Date fecha = null;
        try {

            fecha = formatoDelTexto.parse(strFecha);

        } catch (ParseException ex) {

            ex.printStackTrace();

        }

        java.sql.Date fin2 = new java.sql.Date(fecha.getTime());
        return fin2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtTotalPagar2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnProducto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAgregarProd = new javax.swing.JButton();
        btnQuitarProd = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtStock = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaDetalle = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total a Pagar:");

        txtTotalPagar2.setEditable(false);
        txtTotalPagar2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N

        setClosable(true);
        setTitle("Generador de Facturas");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Factura Nro:");
        jLabel1.setToolTipText("");

        txtNumFactura.setEditable(false);
        txtNumFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNumFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Fecha emisión:");
        jLabel13.setToolTipText("");

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ruc/CI:");

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cod. Producto:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnProducto.setText("Buscar producto");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Producto:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cantidad:");

        btnAgregarProd.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnAgregarProd.setText("Agregar");
        btnAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProdActionPerformed(evt);
            }
        });

        btnQuitarProd.setText("Quitar");
        btnQuitarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProdActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Stock:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Correo:");

        txtCorreo.setEditable(false);
        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cliente:");

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Telefono:");

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Celular:");

        txtCelular.setEditable(false);
        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Dirección:");

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        txtStock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNombreProducto.setBackground(new java.awt.Color(23, 114, 188));
        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(392, 392, 392))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(69, 69, 69)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(53, 53, 53)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnQuitarProd)
                                .addGap(63, 63, 63)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(54, 54, 54)
                                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel17))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCelular)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(btnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(btnQuitarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12)))
                .addGap(62, 62, 62))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel17))
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1030, 270));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblTablaDetalle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblTablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Código", "Producto", "Cantidad", "Valor Unitario", "Subtotal", "Iva", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblTablaDetalle);
        if (tblTablaDetalle.getColumnModel().getColumnCount() > 0) {
            tblTablaDetalle.getColumnModel().getColumn(0).setMinWidth(50);
            tblTablaDetalle.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblTablaDetalle.getColumnModel().getColumn(0).setMaxWidth(50);
            tblTablaDetalle.getColumnModel().getColumn(1).setMinWidth(100);
            tblTablaDetalle.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblTablaDetalle.getColumnModel().getColumn(1).setMaxWidth(100);
            tblTablaDetalle.getColumnModel().getColumn(3).setMinWidth(70);
            tblTablaDetalle.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblTablaDetalle.getColumnModel().getColumn(3).setMaxWidth(70);
            tblTablaDetalle.getColumnModel().getColumn(4).setMinWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(4).setPreferredWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(4).setMaxWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(5).setMinWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(5).setPreferredWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(5).setMaxWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(6).setMinWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(6).setPreferredWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(6).setMaxWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(7).setMinWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(7).setPreferredWidth(130);
            tblTablaDetalle.getColumnModel().getColumn(7).setMaxWidth(130);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGenerarVenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGenerarVenta.setText("Generar Venta");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total a Pagar :");

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Iva 12 % :");

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Subtotal :");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 327, 1030, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        EnviarBuscarCliente();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        // TODO add your handling code here:
        EnviarBuscarProducto();
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProdActionPerformed
        // TODO add your handling code here:

        boolean r = validarNumeroNegativo(txtCantidad.getText());
        if (r == true) {
            JOptionPane.showMessageDialog(this, "Solo números Positivos");
        } else {
            agregarProducto();
            borrarProducto();
        }


    }//GEN-LAST:event_btnAgregarProdActionPerformed

    private void btnQuitarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProdActionPerformed
        // TODO add your handling code here:
        int r;
        if (tblTablaDetalle.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {

            r = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar este producto?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
                double subtotal = 0, iva = 0, total = 0;

                subtotal = Double.parseDouble(modelo.getValueAt(tblTablaDetalle.getSelectedRow(), 5).toString());
                iva = Double.parseDouble(modelo.getValueAt(tblTablaDetalle.getSelectedRow(), 6).toString());
                total = Double.parseDouble(modelo.getValueAt(tblTablaDetalle.getSelectedRow(), 7).toString());

                iva = Double.parseDouble(txtIva.getText()) - iva;
                total = Double.parseDouble(txtTotalPagar.getText()) - total;
                subtotal = Double.parseDouble(txtSubtotal.getText()) - subtotal;

                sub = Float.parseFloat(String.valueOf(subtotal));
                iv = Float.parseFloat(String.valueOf(iva));
                tot = Float.parseFloat(String.valueOf(total));

                txtSubtotal.setText(String.format(Locale.US, "%.2f", sub));
                txtIva.setText(String.format(Locale.US, "%.2f", iv));
                txtTotalPagar.setText(String.format(Locale.US, "%.2f", tot));
                modelo.removeRow(tblTablaDetalle.getSelectedRow());
            }
            borrarProducto();
        }
    }//GEN-LAST:event_btnQuitarProdActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        enviarDatosFacCab();
        enviarDatosFacDetalle();
        CrearPDF();
        //enviarCorreo;
        
        limpiarfactura();
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        limpiarfactura();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    public void CrearPDF(){
        try {
            conexion.conectar();
            File reporte = new File("src/ec/edu/ups/reporte/factura.jasper");
            JasperReport reportejasper=(JasperReport)JRLoader.loadObject(reporte);
            Map parametro=new HashMap();
            int codigo=conFactura.recuperarNunFacturaCab();
            parametro.put("codigo", codigo);
            JasperPrint jasperPrint= JasperFillManager.fillReport(reportejasper, parametro,conexion.getConexion());
            
            JasperExportManager.exportReportToPdfFile(jasperPrint,"Factura.pdf");
            JasperViewer.viewReport(jasperPrint,false);
            
            conexion.desconectar();
            
        } catch (JRException ex) {
            
        }
    }
    
    
    public void enviarCorreo(){
        correo.setContraseña("");// generar con correo que va a enviar desde el video
        correo.setUsuarioCorreo("");//Correo con el que se va a enviar 
        correo.setAsunto("Factura");
        correo.setMensaje("a continuacion se le envia la factura");
        correo.setDestino(txtCorreo.getText().trim());
        correo.setNombreArchivo("Factura.pdf");
        correo.setRutaArchivo("Factura.pdf");
        
        if(controladorCorreo.correoEnviado(correo)){
            JOptionPane.showMessageDialog(this, "correo enviado");
        }else{
            JOptionPane.showMessageDialog(this, "correo no enviado");
        }
        
    }
    public void limpiarfactura() {
        limpiarTabla();
        txtCedula.setText("");
        txtCelular.setText("");
        txtCliente.setText("");
        txtCodigo.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtFecha.setText(getFechaActual());
        txtIva.setText("");
        txtNombreProducto.setText("");
        Idfactura();
        txtCantidad.setText("");
        txtStock.setText("");
        txtSubtotal.setText("");
        txtTelefono.setText("");
        txtTotalPagar.setText("");
//         txtSpiner.set("");
    }

    public void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void actualizarStock() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Producto pro = new Producto();
            idProd = Integer.parseInt(tblTablaDetalle.getValueAt(i, 0).toString());
            cantidad = Integer.parseInt(tblTablaDetalle.getValueAt(i, 3).toString());

            pro = conFactura.buscarIdProducto(idProd);
            double stockAct = pro.getPrd_stock() - cantidad;
            conFactura.actualizarStock(stockAct, idProd);
        }
    }

    public void enviarDatosFacCab() {
        int idCabecera = 0; // esto va en el controlador con la secuencia.
        String numFactura = txtNumFactura.getText();
        Date fecha = formatoFecha();
        double subTotal = Double.parseDouble(txtSubtotal.getText());
        double iva = Double.parseDouble(txtIva.getText());
        double total = Double.parseDouble(txtTotalPagar.getText());
        String anulado = "f";
        int idCliente = cliente.getCli_id();
        int idUsuario = 1; // falta eseta parde del susuario.
        facCabecera = new Factura(idCabecera, numFactura, fecha, subTotal, iva, total, anulado, idCliente, idUsuario);
        conFactura.GuardarFacCabecera(facCabecera);
    }

    public void enviarDatosFacDetalle() {
        int idDetalle = 0; // aqui va la secuencia
        int idCabecera = 0; /// aqui va la secuencia del ID cabecera

        for (int i = 0; i < tblTablaDetalle.getRowCount(); i++) {

            int fIdProd = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            double fcantidad = Double.parseDouble(modelo.getValueAt(i, 3).toString());
            double fprecio = Double.parseDouble(modelo.getValueAt(i, 4).toString());
            double fsubtotal = Double.parseDouble(modelo.getValueAt(i, 5).toString());
            double fIva = Double.parseDouble(modelo.getValueAt(i, 6).toString());
            double ftotal = Double.parseDouble(modelo.getValueAt(i, 7).toString());

            detallefac.setIdDetalle(idDetalle);
            detallefac.setCantidad(fcantidad);
            detallefac.setPrecio(fprecio);
            detallefac.setSubTotal(fsubtotal);
            detallefac.setIva(fIva);
            detallefac.setTotal(ftotal);
            detallefac.setIdCabecera(idCabecera);
            detallefac.setIdProducto(fIdProd);
            conFactura.GuardarFacDetalle(detallefac);
        }
    }

    public void agregarProducto() {

        double total = 0;
        double subtotal = 0;

        modelo = (DefaultTableModel) tblTablaDetalle.getModel();
        int codBarra = Integer.parseInt(producto.getPrd_cbarra());
        String nomProducto = producto.getPrd_nombre();
        precio = producto.getPrd_precio();
        cantidad = Double.parseDouble((txtCantidad.getText()));
        validarNumeroNegativo(String.valueOf(cantidad));
        double stock = Double.parseDouble(txtStock.getText());

        total = cantidad * precio;
        subtotal = total;
        double iva = calcularIvaPorProducto(total);
        total = total + iva;

        pSubtotal = Float.parseFloat(String.valueOf(subtotal));

        //txtTotalPagar.setText(String.format(Locale.US, "%.2f", pIva));
        pIva = Float.parseFloat(String.valueOf(iva));
        //txtTotalPagar.setText(String.format(Locale.US, "%.2f", pIva));

        pTotal = Float.parseFloat(String.valueOf(total));
        //txtTotalPagar.setText(String.format(Locale.US, "%.2f", pTotal));

        ArrayList lista = new ArrayList();

        if (stock > 0 && stock >= cantidad) {

            double s = Double.parseDouble(txtStock.getText());
            double contStock = s - cantidad;
            if (cantidad > s) {
                JOptionPane.showMessageDialog(null, "Sin stock", "Advertencia", JOptionPane.ERROR_MESSAGE);

            } else {

                txtStock.setText(String.format(Locale.US, "%.2f", contStock));

            }

            lista.add(idProd);
            lista.add(codBarra);
            lista.add(nomProducto);
            lista.add(cantidad);
            lista.add(precio);
            lista.add(pSubtotal);
            lista.add(pIva);
            lista.add(pTotal);

            Object[] ob = new Object[8];
            ob[0] = lista.get(0);
            ob[1] = lista.get(1);
            ob[2] = lista.get(2);
            ob[3] = lista.get(3);
            ob[4] = lista.get(4);
            ob[5] = lista.get(5);
            ob[6] = lista.get(6);
            ob[7] = lista.get(7);
            modelo.addRow(ob);
            tblTablaDetalle.setModel(modelo);

            calcularSubtotal(modelo);
            calcularIvaTotal(modelo);
            calcularTotalApagar(modelo);

        } else {
            JOptionPane.showMessageDialog(this, "Stock del producto no disponible");
        }
    }

    public void calcularIvaTotal(DefaultTableModel modelo) {
        double iva = 0;
        double filaTotal = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            filaTotal = Double.parseDouble(modelo.getValueAt(i, 6).toString());
            iva = iva + filaTotal;
        }
        float pIva = 0;
        pIva = Float.parseFloat(String.valueOf(iva));
        txtIva.setText(String.format(Locale.US, "%.2f", pIva));
    }

    public void calcularSubtotal(DefaultTableModel modelo) {
        double sub = 0;
        double filaTotal = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            filaTotal = Double.parseDouble(modelo.getValueAt(i, 5).toString());
            sub = sub + filaTotal;
        }
        float pSubtotal = 0;
        pSubtotal = Float.parseFloat(String.valueOf(sub));
        txtSubtotal.setText(String.format(Locale.US, "%.2f", pSubtotal));
    }

    public void calcularTotalApagar(DefaultTableModel modelo) {
        double total = 0;
        double filaTotal = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            filaTotal = Double.parseDouble(modelo.getValueAt(i, 7).toString());
            total = total + filaTotal;
        }
        float ptotal = 0;
        ptotal = Float.parseFloat(String.valueOf(total));
        txtTotalPagar.setText(String.format(Locale.US, "%.2f", ptotal));
    }

    public void borrarProducto() {
        txtCodigo.setText("");
        txtStock.setText("");
        txtNombreProducto.setText("");
    }

    public double calcularIvaPorProducto(double tot) {
        double totalIva = 0;
        boolean iva = producto.getPrd_iva();
        if (iva == true) {
            totalIva = (tot * 12) / 100;
        } else {
            totalIva = 0;
        }
        return totalIva;
    }

    public void EnviarBuscarProducto() {
        String codigo = txtCodigo.getText();

        producto = conFactura.buscarProducto(codigo);
        idProd = producto.getPrd_id();
        //System.out.println("pruega-- = " + producto.getPrd_nombre());

        if (producto.getPrd_cbarra() != null) {

            txtStock.setText(Double.toString(producto.getPrd_stock()));
            txtNombreProducto.setText(producto.getPrd_nombre());

        } else {
            JOptionPane.showMessageDialog(this, "El código ingresado es incorrecto", "Producto no registrado", JOptionPane.OK_OPTION);
        }

    }

    public void EnviarBuscarCliente() {
        String cedula = txtCedula.getText();

        cliente = conFactura.buscarCliente(cedula);
        if (cliente.getCli_cedula() != null) {

            txtCliente.setText(cliente.getCli_nombre() + " " + cliente.getCli_apellido());
            txtDireccion.setText(cliente.getCli_direccion());
            txtCelular.setText(cliente.getCli_celular());
            txtTelefono.setText(cliente.getCli_tel_convencional());
            txtCorreo.setText(cliente.getCli_correo_electronico());

        } else {
            JOptionPane.showMessageDialog(this, "La cedula ingresada no está registrada", "Cliente no registrado", JOptionPane.OK_OPTION);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProd;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnQuitarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblTablaDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva;
    private javax.swing.JLabel txtNombreProducto;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JLabel txtStock;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtTotalPagar2;
    // End of variables declaration//GEN-END:variables
}
